# Generated by Django 2.2.1 on 2019-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_and_can',
            name='yolo',
            field=models.BooleanField(default=True, verbose_name='yolov3 object detection'),
        ),
    ]
